# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            wi ai
tagline:          'wiai'
description:      'haxe sarma press'
baseurl:          /
version:          0.1

author:
  name:           'wi ai'
  url:            https://wiai.github.io

paginate:         1

gems:             [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

github:
  repo:           https://github.com/wiai/wiai.github.io/

tags:


